### ISSUE TITLE
Unable to specify "all errors or exceptions"

### ISSUE THREAD

**Issue by ijcd** [safwank/ElixirRetry#16]
This library only catching `RuntimeError` by default bit me. I lost a few days on this. I added a PR to improve the README.

However, my expectation was that since there was a `rescue_only`, that the default was *everything*. I don't think that assumption is unreasonable.

Would you accept a PR to change the default to be capture everything? If not, how about some way to specify everything? 

In my use case, an :ets table is being accessed at startup before it has been populated. The error thrown is `ArgumentError`.

This does not work, but I expected it would:

```
defmodule Foo do
  use Retry

  def go do
  	retry with: lin_backoff(10, 2) |> cap(1_000) |> Stream.take(10) do
  	  IO.puts "once"
  	  raise ArgumentError.exception("test")
    end
  end
end

Foo.go()
```

**Comment by safwank** [comment]
Hi @ijcd. I'm of the opinion that rescuing everything by default isn't a good idea. If you have programming errors (incorrect arguments, function clause errors, etc) in your code, you probably don't want to retry them. `RuntimeError` is the default for legacy reasons and because semantically it serves as a catch-all for non-programming-related errors.
